done task 4-styling
demasha0908/fe-react-2024 pull request #4
Opened 2024-05-21 20:41 UTC by demasha0908

https://demasha0908.github.io/fe-react-2024/

- [ ]  Mentor is added to pr
- [ ]  AC copied to pr description
- [ ]  Link to deployed version is added to pr
- [ ]  Added layout of Search Bar
- [ ]  Rewritten all styles with Module Styles
- [ ]  Implemented dynamic theme change logic

2024-05-22 09:56 UTC, vladyslav-yermolin-moc requested changes
Thanks for a good work, @demasha0908

2024-05-22 09:56 UTC, vladyslav-yermolin-moc commented on src/components/product/ProductList.component.tsx
> +    <section className={styles.product__section}>
Please correct border and searc text color 
<img width="971" alt="image" src="https://github.com/demasha0908/fe-react-2024/assets/98031768/9da731fd-9748-495c-a008-5abd7925ad2e">

2024-05-22 09:56 UTC, vladyslav-yermolin-moc commented on src/components/searchbar/SearchBar.module.css
> +  border-radius: 20px;
Please correct border-radius
<img width="776" alt="image" src="https://github.com/demasha0908/fe-react-2024/assets/98031768/fefcd566-3190-461e-b555-83d7540b4c56">

2024-05-22 09:56 UTC, vladyslav-yermolin-moc commented on src/components/footer/footer.module.css
Please correct 
- separator color and gap to the page edge and to the page content
- Padding of the footer's text
<img width="1254" alt="image" src="https://github.com/demasha0908/fe-react-2024/assets/98031768/e9554402-d8fc-404c-8b3f-97be4ab1d72a">

2024-05-22 09:56 UTC, vladyslav-yermolin-moc commented on src/App.tsx
> +                <HeaderComponent shouldShowAbout={shouldShowAbout} toggleAboutState={toggleAbout} showTheme={changeTheme} />
```suggestion
                <HeaderComponent shouldShowAbout={shouldShowAbout} toggleAboutState={toggleAbout} changeTheme={changeTheme} />
```

2024-05-22 09:56 UTC, vladyslav-yermolin-moc commented on src/App.tsx
> +        const stateTheme = theme === 'light' ? 'dark' : 'light';
```suggestion
        const newTheme = theme === 'light' ? 'dark' : 'light';
```

2024-05-23 11:04 UTC, demasha0908 commented on src/components/searchbar/SearchBar.module.css
> +  border-radius: 20px;
fixed

2024-05-23 11:04 UTC, demasha0908 commented on src/components/footer/footer.module.css
fixed

2024-05-23 11:04 UTC, demasha0908 commented on src/App.tsx
> +                <HeaderComponent shouldShowAbout={shouldShowAbout} toggleAboutState={toggleAbout} showTheme={changeTheme} />
fixed

2024-05-23 11:05 UTC, demasha0908 commented on src/App.tsx
> +        const stateTheme = theme === 'light' ? 'dark' : 'light';
fixed

2024-05-23 19:44 UTC, vladyslav-yermolin-moc commented
Hey, @demasha0908, thanks for your fixes.
Something happened with your light theme - here is screencast with description

https://github.com/demasha0908/fe-react-2024/assets/98031768/b70ff596-3a0d-4425-8a2c-b9c1b509e23b

2024-05-23 19:46 UTC, vladyslav-yermolin-moc requested changes
Please see my comment.
Also pay attantion to the active state of the icons of themes: sun and moon.

2024-05-25 08:02 UTC, vladyslav-yermolin-moc approved these changes
Thanx for your fixes, @demasha0908 !
Please correct in the next pr 
![image](https://github.com/demasha0908/fe-react-2024/assets/98031768/02375a81-e7d8-4375-895c-414c157e6c92)

2024-05-25 08:02 UTC, merged