Task/05 hooks
demasha0908/fe-react-2024 pull request #5
Opened 2024-06-03 20:35 UTC by demasha0908

https://demasha0908.github.io/fe-react-2024/

Acceptance Criteria for 1
 

- [ ] Mentor is added to pr
- [ ]  AC copied to pr description
- [ ]  Link to deployed version is added to pr
- [ ]  Simple Pagination component (without ...) is added and works correctly
- [ ]  On the 1st page button Back should be disabled, same as button Forward on the last page
- [ ]  Interaction with pagination should not change or break sorting and filtration.
- [ ]  Category filter (multi-select) is added and works correctly
- [ ]  Sorting input (single select) is added and works correctly
- [ ]  Interaction with filter and sorter should reset pagination and move a user to the 1st page

Acceptance Criteria for 1*

- [ ]  Pagination component with ... is implemented according to [design](
- [ ]  Search input works correctly

2024-06-03 21:10 UTC, demasha0908 commented
Sorry, I don't know how to fix error :(

2024-06-04 07:30 UTC, vladyslav-yermolin-moc commented on src/components/searchbar/SearchBar.component.tsx
> +    }, [activeFilter, searchTerm, activeCategories, products, currentPage]);
quick fix:
```suggestion
    }, [activeFilter, searchTerm, activeCategories, products, currentPage, onFilteredProducts]);
```
Linter said: `onFilteredProducts` is a variable (function in this case) you are using inside the `useEffect` hook. So you should add this variable to the dependencies of the hook.

2024-06-04 07:31 UTC, vladyslav-yermolin-moc commented
Thanks for your pr, will check it during the day

2024-06-04 19:50 UTC, vladyslav-yermolin-moc requested changes
So good so far 👍

2024-06-04 19:50 UTC, vladyslav-yermolin-moc commented on src/components/product/Pagination.module.css
> +.arrowButton:hover {
Please correct the color of disabled `>` - should be `#ccc`
Also would be good to block any interaction with disabled button - not change bg-color on hover and change the cursor to default
![image](https://github.com/demasha0908/fe-react-2024/assets/98031768/bd0dcc24-c36f-4929-9bb7-5136b215ed4d)

2024-06-04 19:50 UTC, vladyslav-yermolin-moc commented on src/components/product/Pagination.component.tsx
> +        }
Using the hooks inside of the conditions is a bad practice.
```suggestion
        if (activePage >= totalPages) {
          return;
        }
            const newPage = activePage + 1;
            setActivePage(newPage);
            onPageChange(newPage);
```

2024-06-04 19:50 UTC, vladyslav-yermolin-moc commented on src/components/product/Pagination.component.tsx
> +        }
same here

2024-06-04 19:50 UTC, vladyslav-yermolin-moc commented on src/components/product/Pagination.component.tsx
> +                    className={
would be good to move this logic to separate method or use [classNames](https://github.com/JedWatson/classnames)

2024-06-04 19:50 UTC, vladyslav-yermolin-moc commented on src/components/product/Pagination.component.tsx
> +    const getPagination = (): (string | number)[] => {
Would be good to move outside of the component, into some `helper.ts`

2024-06-04 19:50 UTC, vladyslav-yermolin-moc commented on src/components/product/Pagination.component.tsx
> +                    disabled={typeof page === 'string'}
This condition is implicit. Make it explicit
```suggestion
const DOTS = '...'

                    disabled={page === DOTS}
```

2024-06-04 19:50 UTC, vladyslav-yermolin-moc commented on src/components/product/Pagination.component.tsx
Looks like you need separate folder `pagination` for these two files

2024-06-04 19:50 UTC, vladyslav-yermolin-moc commented on src/components/product/ProductCard.component.tsx
> +import React from 'react';
Do you need this here?

2024-06-04 19:50 UTC, vladyslav-yermolin-moc commented on src/components/product/ProductList.component.tsx
> +    });
Please add a dependecies - now useEffect makes a request on every rerender and DDOSes our backend)))
![image](https://github.com/demasha0908/fe-react-2024/assets/98031768/b0f33e22-d600-4991-adbf-a185c7303b39)

2024-06-04 19:50 UTC, vladyslav-yermolin-moc commented on src/components/product/Products.component.tsx
> +import React from 'react';
You can skip this line everywhere https://stackoverflow.com/questions/71725865/do-i-need-to-import-react-in-every-file

2024-06-05 19:20 UTC, vladyslav-yermolin-moc requested changes

2024-06-05 19:20 UTC, vladyslav-yermolin-moc commented on src/components/product/ProductList.component.tsx
> +        setPaginatedProducts(paginated);
you set state two times

2024-06-05 19:20 UTC, vladyslav-yermolin-moc commented on src/components/product/ProductList.component.tsx
> +    const [paginatedProducts, setPaginatedProducts] = useState<Product[]>([]);
```suggestion
    const [shownProducts, ...
```
or
```suggestion
    const [productsOnPage, ...```

2024-06-05 19:20 UTC, vladyslav-yermolin-moc commented on src/components/searchbar/SearchBar.component.tsx
in this component not only SearchBar. Proly Filters is a right name

2024-06-05 19:20 UTC, vladyslav-yermolin-moc commented on src/components/searchbar/SearchBar.component.tsx
Lift up all logic from here.
Idealy would be great to split this component into 3 pieces:
- search
- sort
- category
Every component should get state and aetter from parent, like `selectedCategories` and `setSelectedCategories`. And only show selected cats and send to the parent event of selecting

2024-06-06 20:35 UTC, demasha0908 commented on src/components/searchbar/SearchBar.component.tsx
fixed

2024-06-08 11:13 UTC, vladyslav-yermolin-moc approved these changes

2024-06-08 11:13 UTC, merged